const Data = [
  {
    id: 1,
    img: "./images/image 12.png",
    rating: "5.0",
    reviewCount: "6",
    country: "USA",
    title: "Life Lessons with Katie Zaferes",
    price: "136",
    openSpots: 0,
  },
  {
    id: 2,
    img: "./images/mountain-bike 1.png",
    rating: "4.5",
    reviewCount: "10",
    country: "Online",
    title: "Life Lessons with Katie Zaferes",
    price: "200",
    openSpots: 27,
  },
  {
    id: 3,
    img: "./images/wedding-photography 1.png",
    rating: "4.9",
    reviewCount: "4",
    country: "Britin",
    title: "Life Lessons with Katie Zaferes",
    price: "70",
    openSpots: 3,
  },
  {
    id: 4,
    img: "./images/image 12.png",
    rating: "5.0",
    reviewCount: "6",
    country: "USA",
    title: "Life Lessons with Katie Zaferes",
    price: "136",
    openSpots: 0,
  },
  {
    id: 5,
    img: "./images/mountain-bike 1.png",
    rating: "4.5",
    reviewCount: "10",
    country: "Online",
    title: "Life Lessons with Katie Zaferes",
    price: "200",
    openSpots: 27,
  },
  {
    id: 6,
    img: "./images/wedding-photography 1.png",
    rating: "4.9",
    reviewCount: "4",
    country: "Britin",
    title: "Life Lessons with Katie Zaferes",
    price: "70",
    openSpots: 3,
  },
];

export default Data;
